FROM python:3.7.9-buster

ENV CONTAINER_HOME=/var/www

ADD ./flask $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN apt-get update && apt-get install -y supervisor

RUN pip install -r $CONTAINER_HOME/requirements.txt

ENV PATH $CONTAINER_HOME/src:$PATH
